version: 2.1

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - run:
          name: Install trivy
          command: |
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )

            wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
      - run:
          name: Scan the local image with trivy
          command: ./trivy --exit-code 0 --no-progress $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - slack/status:
          success_message: ':tada: build successful!!'
          failure_message: ':red_circle: build failed...'
          webhook: $SLACK_WEBHOOK

orbs:
  docker: circleci/docker@1.3.0
  slack: circleci/slack@3.4.2

workflows:
  tagged-build:
    jobs:
      - build-and-push:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/