version: 2.1

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          digest-path: /tmp/digest.txt
          image: otajisan/vulnerable-python-docker-example
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  notify-slack:
    executor: container
    steps:
      - slack/status:
          success_message: ':tada: build successful!!'
          failure_message: ':red_circle: build failed...'
          webhook: $SLACK_WEBHOOK

orbs:
  docker: circleci/docker@1.3.0
  snyk: snyk/snyk@0.0.10
  slack: circleci/slack@3.4.2

workflows:
  commit:
    jobs:
      - build-and-push
      - notify-slack